import { join } from "path";
import { homedir } from "os";
import { existsSync, readdirSync, statSync, readFileSync, writeFileSync } from "fs";

import type { PlatformAdapter, InstallItem, InstallPreview } from "../shared/types";
import { ensureDir, copyDirRecursive, log, SKILLS_TO_INSTALL, VERSION } from "../../scripts/utils";

const JUNIE_DIR = join(homedir(), ".junie");
const JUNIE_SKILLS_DIR = join(JUNIE_DIR, "skills");
const JUNIE_AGENTS_DIR = join(JUNIE_DIR, "agents");
const JUNIE_GUIDELINES_FILE = join(JUNIE_DIR, "AGENTS.md");

// Simple single-line YAML parser. Handles `key: value` pairs only.
// Does NOT support multi-line values, block scalars, or indented lists.
// Sufficient for our agent definitions which use simple key-value frontmatter.
function parseFrontmatter(content: string): { frontmatter: Record<string, string>; body: string } {
  const match = content.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) return { frontmatter: {}, body: content };

  const frontmatter: Record<string, string> = {};
  for (const line of match[1].split("\n")) {
    const colonIdx = line.indexOf(":");
    if (colonIdx === -1) continue;
    const key = line.slice(0, colonIdx).trim();
    const value = line.slice(colonIdx + 1).trim();
    if (key) frontmatter[key] = value;
  }

  return { frontmatter, body: match[2] };
}

function serializeFrontmatter(frontmatter: Record<string, string>, body: string): string {
  const lines = Object.entries(frontmatter).map(([k, v]) => `${k}: ${v}`);
  return `---\n${lines.join("\n")}\n---\n${body}`;
}

function transformAgentForJunie(content: string): string {
  const { frontmatter, body } = parseFrontmatter(content);
  const { permissionMode: _dropped, ...junieFrontmatter } = frontmatter;
  return serializeFrontmatter(junieFrontmatter, body);
}

function generateAgentsMd(): string {
  return `# ima-claude: AI Coding Agent Guidelines

> Generated by ima-claude v${VERSION} for Junie CLI.
> Source: https://github.com/Soabirw/ima-claude

## Default Persona: The Practitioner

A 25-year software development veteran. FP-first, composition-minded, anti-over-engineering.
Uses "we" not "I" — collaborative, humble, light-hearted. "Slow is smooth, smooth is fast."

**Philosophy**: Simple > Complex | Evidence > Assumptions | Native > Utilities | MVP > Enterprise

---

## Memory Routing

| Store what | Where | Why |
|---|---|---|
| Decisions, preferences, patterns, bugs | Vestige \`smart_ingest\` | Fades naturally if not referenced |
| Reference material (docs, standards, PRDs) | Qdrant \`qdrant-store\` | Permanent library |
| Session state, task progress | Serena \`write_memory\` | Project-scoped workbench |
| Future reminders | Vestige \`intention\` | Surfaces at next session |

At session start, check memory before asking questions:
- Vestige: search for user preferences and project context
- Vestige: check for pending reminders/intentions
- Serena: list memories if in a Serena-activated project

Auto-store: "I prefer..." → Vestige preference. "Let's go with X because..." → Vestige decision. "The reason this failed..." → Vestige bug.

After completing work: store outcome in Vestige, reference material in Qdrant, session state in Serena.

---

## Orchestrator Protocol

You are the Orchestrator. Plan and delegate. Do NOT implement directly.
- Non-trivial work → task-planner (decompose) → task-runner (delegate)
- Trivial = single file, < 5 lines, no judgment calls
- Model selection: opus for orchestration, sonnet for implementation (default), haiku for lookups

---

## Available Agents

Delegate to named agents — they enforce model, tools, and permissions automatically.

| Agent | Model | Use For |
|---|---|---|
| \`explorer\` | haiku | File discovery, codebase exploration |
| \`implementer\` | sonnet | Feature dev, bug fixes, refactoring |
| \`reviewer\` | sonnet | Code review, security audit, FP checks |
| \`wp-developer\` | sonnet | WordPress plugins, themes, WP-CLI, forms |
| \`memory\` | sonnet | Memory search, storage, consolidation |

---

## Code Navigation (Serena)

When Serena MCP is available, **prefer Serena over Read/Grep for code investigation.** 40-70% token savings.

| Instead of | Use |
|---|---|
| Read file to understand structure | Serena get_symbols_overview |
| Grep for class/function definition | Serena find_symbol |
| Grep for callers/references | Serena find_referencing_symbols |

Use Read only when you need the actual implementation body of a known, specific symbol.

---

## Complex Reasoning

Use sequential thinking before acting on:
- Debugging / root cause analysis / "why is this failing"
- Trade-off evaluation / "which approach"
- Architectural decisions / design choices
- Multi-step investigations where approach may change

---

## MCP Tool Routing

| Signal | Preferred Tool |
|---|---|
| "latest", "2025/2026", "what's new" | Tavily search |
| Library/framework API question | Context7 |
| URL content extraction | Tavily extract (use advanced for complex pages) |

Before web tools: check internal knowledge → Context7 → then Tavily.
Before external lookups: check Vestige memory first.

---

## Search Preference

Always prefer \`rg\` (ripgrep) over grep/find. Faster, respects .gitignore, recursive by default.

---

## Security

- Verify nonce usage and input sanitization in WordPress PHP code
- Never concatenate user input directly into SQL — use parameterized queries
- Check for XSS, CSRF, and OWASP top 10 vulnerabilities in written code

---

## Code Style

- Don't create custom FP utility functions (pipe, compose, curry) — use language-native patterns or established libraries
- In WordPress JavaScript context, use jQuery patterns when jQuery is already loaded
- Prefer Bootstrap utility classes over custom CSS overrides
- Run \`composer dump-autoload\` after creating new PHP files
- Use proper Edit tools for code changes, not sed/awk

---

## Documentation

Follow the three-tier documentation system:
- **Active** — Living docs, kept current (README, API docs, architecture)
- **Archive** — Historical reference, rarely updated (decisions, post-mortems)
- **Transient** — Ephemeral, git-ignored (session notes, scratch)
`;
}

export class JunieAdapter implements PlatformAdapter {
  readonly name = "junie";
  readonly displayName = "Junie CLI";
  readonly configDir = JUNIE_DIR;

  detect(): boolean {
    return existsSync(JUNIE_DIR);
  }

  preview(sourceDir: string): InstallPreview {
    const skillItems: InstallItem[] = SKILLS_TO_INSTALL.map((skill) => ({
      name: skill,
      category: "skill" as const,
      destPath: join(JUNIE_SKILLS_DIR, skill),
      exists: existsSync(join(JUNIE_SKILLS_DIR, skill)),
    })).filter((item) => existsSync(join(sourceDir, "skills", item.name)));

    const agentsDir = join(sourceDir, "agents");
    const agentItems: InstallItem[] = existsSync(agentsDir)
      ? readdirSync(agentsDir)
          .filter((f) => f.endsWith(".md"))
          .map((file) => ({
            name: file.replace(/\.md$/, ""),
            category: "agent" as const,
            destPath: join(JUNIE_AGENTS_DIR, file),
            exists: existsSync(join(JUNIE_AGENTS_DIR, file)),
          }))
      : [];

    const guidelineItem: InstallItem = {
      name: "AGENTS.md",
      category: "guideline",
      destPath: JUNIE_GUIDELINES_FILE,
      exists: existsSync(JUNIE_GUIDELINES_FILE),
    };

    return {
      platform: this.name,
      targetDir: JUNIE_DIR,
      items: [...skillItems, ...agentItems, guidelineItem],
    };
  }

  installSkills(sourceDir: string, exclude?: string[]): void {
    ensureDir(JUNIE_SKILLS_DIR);
    const skills = exclude?.length
      ? SKILLS_TO_INSTALL.filter((s) => !exclude.includes(s))
      : SKILLS_TO_INSTALL;
    for (const skill of skills) {
      const src = join(sourceDir, skill);
      if (existsSync(src) && statSync(src).isDirectory()) {
        copyDirRecursive(src, join(JUNIE_SKILLS_DIR, skill));
        log.step(`skill: ${skill}`);
      }
    }
  }

  installAgents(sourceDir: string, exclude?: string[]): void {
    ensureDir(JUNIE_AGENTS_DIR);
    const entries = readdirSync(sourceDir)
      .filter((f) => f.endsWith(".md"))
      .filter((f) => !exclude?.includes(f.replace(/\.md$/, "")));
    for (const file of entries) {
      const content = readFileSync(join(sourceDir, file), "utf8");
      const transformed = transformAgentForJunie(content);
      writeFileSync(join(JUNIE_AGENTS_DIR, file), transformed);
      log.step(`agent: ${file}`);
    }
  }

  installGuidelines(_pluginRoot: string): void {
    ensureDir(JUNIE_DIR);
    writeFileSync(JUNIE_GUIDELINES_FILE, generateAgentsMd());
    log.step(`guidelines: ${JUNIE_GUIDELINES_FILE}`);
  }

  postInstall(): void {
    log.info("Junie install complete. Verify:");
    log.info(`  Skills:     ${JUNIE_SKILLS_DIR}`);
    log.info(`  Agents:     ${JUNIE_AGENTS_DIR}`);
    log.info(`  Guidelines: ${JUNIE_GUIDELINES_FILE}`);
    log.warn("Note: Junie does not support hooks — behavioral guidelines are in AGENTS.md instead.");
  }
}
